name: vca_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python=3.12
  - pandas=2.3
  - numpy=2.3
  - matplotlib=3.10
  - pysam=0.23
  - pysradb=2.5
  - requests
  - bwa
  - samtools
  - bcftools
  - wget
  - ipykernel
  - ipython
  - scipy=1.14.0
  - seaborn=0.13.2